#!/bin/sh
function check() {
	if ! which $1 &> /dev/null; then
		echo "R8 needs $1"
		exit 1
	fi
}

function pkg_check() {
	if ! pkg-config --exists $1; then
		echo "R8 needs $1"
		exit 1
	fi
}

check pkg-config
pkg_check libucw
pkg_check raylib

echo all good
