#!/bin/sh

git clone git://git.ucw.cz/libucw.git
cd libucw

# there is a bug (at least on my machines) that I need to patch
curl https://randacek.dev/dl/ucw-patch | git apply -- &&

# default installation prefix is `/usr/local` but `pkg-config` doesn't look there by default so install it in `/usr` instead.
./configure PREFIX=/usr &&

# the usual
make &&
sudo make install

cd ..

# cleanup
rm libucw -rf

# It's nice to hear it explicitly.
echo libucw installed successfully
